scriptencoding utf-8

if &compatible
    set nocompatible
endif


syntax on

"" Settings
set nocursorline
set nocursorcolumn
set guioptions-=T
set guioptions-=m
set lines=35
set columns=95
set number
set title
set showcmd
set ruler
set showmatch
set matchtime=3
set laststatus=2
set virtualedit=onemore

"" Encode
set fenc=UTF-8
set encoding=UTF-8
set fileencodings=iso2022-jp,euc-jp,sjis,utf-8
set fileformats=unix,dos,mac
set termencoding=UTF-8

"" File/Backup
set hidden
set autoread
set nobackup
set noswapfile
set history=1000

"" Search
set incsearch
set hlsearch
set ignorecase
set smartcase
set wrapscan

"" Input
set cindent
set shiftwidth=2
set tabstop=2
set expandtab
set softtabstop=2
set backspace=indent,eol,start
set whichwrap=b,s,h,l,<,>,[,]
set clipboard=unnamed

"" Scripts
function! ZenkakuSpace()
  highlight ZenkakuSpace cterm=underline ctermfg=darkgrey gui=underline guifg=darkgrey
endfunction

if has('syntax')
  augroup ZenkakuSpace
    autocmd!
    " ZenkakuSpaceをカラーファイルで設定するなら次の行は削除
    autocmd ColorScheme       * call ZenkakuSpace()
    " 全角スペースのハイライト指定
    autocmd VimEnter,WinEnter * match ZenkakuSpace /　/
    autocmd VimEnter,WinEnter * match ZenkakuSpace '\%u3000'
  augroup END
  call ZenkakuSpace()
endif





if !has('gui_running')
  augroup TransparentBG
	  autocmd!
  	autocmd Colorscheme * highlight Normal      ctermbg=NONE guibg=NONE
	  autocmd Colorscheme * highlight NonText     ctermbg=NONE guibg=NONE
	  autocmd Colorscheme * highlight LineNr      ctermbg=NONE guibg=NONE 
	  autocmd Colorscheme * highlight Folded      ctermbg=NONE guibg=NONE 
	  autocmd Colorscheme * highlight EndOfBuffer ctermbg=NONE guibg=NONE 
  augroup END
end


inoremap ( (<C-[>:call InsBraces()<CR>i
inoremap { {}<left>

"move
nnoremap j h
"nnoremap l l
nnoremap ; gk
nnoremap k gj

"Evacuate
nnoremap gk j
nnoremap g; k
nnoremap gj g;
nnoremap h ;

inoremap <A-j> <left>
inoremap <A-k> <down>
inoremap <A-l> <right>
inoremap <A-;> <up>


